site_name: 揚揚教學網 -- 112學年
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.top
    # - navigation.footer
    # - toc.integrate
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: zh-TW
  palette:
    - scheme: default
      # toggle:
      #   icon: material/toggle-switch-off-outline
      #   name: Switch to dark mode
      primary: teal
      accent: purple
    # - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
    #   primary: teal
    #   accent: lime
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html

plugins:
  - search:
      separator: '[\s\u200b\-]'
  # - literate-nav:
  #     nav_file: SUMMARY.md
  #     implicit_index: true

# Page tree
nav:
  - 首頁: index.md
  - 課諮: course_consultation.md
  - 檢定:
    - cert/index.md
    - 丙級:
      - 丙級說明及解題: cert/cert3/cert3.md
    - 乙級:
      - 乙級說明及解題: cert/cert2/cert2.md
      - 題組五: cert/cert2/resolve-5.md
      - 題組四: cert/cert2/resolve-4.md
    - TQC: cert/tqc.md
  - 程式設計:
    - programming/index.md
    - App Inventor: 
      - programming/app_inventor/index.md
      - 開發環境: programming/app_inventor/env.md
      - programming/app_inventor/calculator.md
      - programming/app_inventor/pair_up_fruits/pair_up_fruits.md
    - APCS:
      - programming/apcs/index.md
    - Bebras: programming/bebras.md
  - 資處二甲:
      - dp111/index.md
      # - dp111/course_counseling.md
      - dp111/112_2_dp111_log.md
      - dp111/112_1_dp111_log.md
  - 綜高三乙:
      - bs110/index.md
      - bs110/112_2_bs110_log.md
      - bs110/112_1_bs110_log.md